services:
  - type: web
    name: training-tracker
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefix server && npm install --prefix client --include=dev && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
